### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by BsklWssy** [no5ix/sux#2]
第一个 cap+t 翻译的话 报错 是要翻墙么这个
![Snipaste_2023-04-10_09-39-15](https://user-images.githubusercontent.com/32919368/230809035-70308494-c1c4-4ae1-a78a-2ed2df2ab10b.png)
第二个 用caps的快捷键时 比如 cap+s 按一下确实向左移动了 但是按过之后cap键是触发的 capslock则不会 意思就是按一下cap+s 出发左键 但是cap键不要触发

很好用 把我常用的功能放到一个软件里了 另外 问一下 有没有交流群

**Comment by no5ix** [comment]
1. 我是用chromium内核的浏览器的诶, 你可能需要把你的默认浏览器改为chromium相关的浏览器? 我重现不出来你这个问题
2. 修了, 请使用最新版本哈 https://github.com/no5ix/sux/releases/tag/v0.2.16
3. 加了个交流群, QQ群: 862925073, 加群备注来意, 也可以加微信群, QQ群里有微信群的邀请二维码(这玩意有有效期...)
